version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "doja-liveness-check-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vmqors0t3uqa"
s3_prefix = "doja-liveness-check-stack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
